IF OBJECT_ID('SSOMA.INS_INSPECCION_PARTICIPANTE', 'U') IS NULL
BEGIN
  CREATE TABLE SSOMA.INS_INSPECCION_PARTICIPANTE (
    id_inspeccion INT NOT NULL,
    id_usuario INT NOT NULL,
    orden_custom INT NULL,
    created_at DATETIME2 NOT NULL
      CONSTRAINT DF_INS_INSPECCION_PARTICIPANTE_created_at DEFAULT SYSUTCDATETIME(),
    CONSTRAINT PK_INS_INSPECCION_PARTICIPANTE PRIMARY KEY (id_inspeccion, id_usuario)
  );
END;
GO

IF OBJECT_ID('SSOMA.INS_INSPECCION_PARTICIPANTE', 'U') IS NOT NULL
   AND NOT EXISTS (
     SELECT 1
     FROM sys.foreign_keys
     WHERE name = 'FK_INS_INSPECCION_PARTICIPANTE_INSPECCION'
       AND parent_object_id = OBJECT_ID('SSOMA.INS_INSPECCION_PARTICIPANTE')
   )
BEGIN
  ALTER TABLE SSOMA.INS_INSPECCION_PARTICIPANTE
  ADD CONSTRAINT FK_INS_INSPECCION_PARTICIPANTE_INSPECCION
    FOREIGN KEY (id_inspeccion)
    REFERENCES SSOMA.INS_INSPECCION (id_inspeccion);
END;
GO

IF OBJECT_ID('SSOMA.INS_INSPECCION_PARTICIPANTE', 'U') IS NOT NULL
   AND NOT EXISTS (
     SELECT 1
     FROM sys.foreign_keys
     WHERE name = 'FK_INS_INSPECCION_PARTICIPANTE_USUARIO'
       AND parent_object_id = OBJECT_ID('SSOMA.INS_INSPECCION_PARTICIPANTE')
   )
BEGIN
  ALTER TABLE SSOMA.INS_INSPECCION_PARTICIPANTE
  ADD CONSTRAINT FK_INS_INSPECCION_PARTICIPANTE_USUARIO
    FOREIGN KEY (id_usuario)
    REFERENCES SSOMA.INS_USUARIO (id_usuario);
END;
GO

